import { DEFAULT_RENOVATION_PHASE } from "@/lib/renovation/phases";
import type { RenovationState } from "./types";

export const initialRenovationState: RenovationState = {
  projects: [
    {
      id: "p_kitchen",
      name: "Kitchen Renovation",
      totalBudget: 25000,
      ownContribution: 15000,
      constructionDepotTotal: 10000,
      address: "",
      expectedKeyHandover: null,
      planningStartDate: null,
      notes: "",
    },
    {
      id: "p_bathroom",
      name: "Bathroom Refresh",
      totalBudget: 12000,
      ownContribution: 12000,
      constructionDepotTotal: null,
      address: "",
      expectedKeyHandover: null,
      planningStartDate: null,
      notes: "",
    },
  ],
  rooms: [
    { id: "r_kitchen_demo", name: "Kitchen - Demo", projectId: "p_kitchen" },
    { id: "r_kitchen_install", name: "Kitchen - Install", projectId: "p_kitchen" },
    { id: "r_bath_demo", name: "Bathroom - Demo", projectId: "p_bathroom" },
  ],
  tasks: [
    {
      id: "t_kitchen_demolish",
      projectId: "p_kitchen",
      title: "Remove old cabinet boxes",
      roomIds: ["r_kitchen_demo"],
      renovationPhase: DEFAULT_RENOVATION_PHASE,
      status: "todo",
      durationDays: 2,
      priority: "medium",
      description: "",
      sortOrder: 0,
      startDate: null,
      assignedRosterId: null,
      fundedByConstructionDepot: false,
    },
    {
      id: "t_kitchen_plumb",
      projectId: "p_kitchen",
      title: "Check plumbing rough-in",
      roomIds: ["r_kitchen_install"],
      renovationPhase: DEFAULT_RENOVATION_PHASE,
      status: "doing",
      durationDays: 1,
      priority: "high",
      description: "",
      sortOrder: 0,
      startDate: null,
      assignedRosterId: null,
      fundedByConstructionDepot: false,
    },
    {
      id: "t_bath_tile",
      projectId: "p_bathroom",
      title: "Plan tile layout",
      roomIds: ["r_bath_demo"],
      renovationPhase: DEFAULT_RENOVATION_PHASE,
      status: "done",
      durationDays: 1,
      priority: "low",
      description: "",
      sortOrder: 0,
      startDate: null,
      assignedRosterId: null,
      fundedByConstructionDepot: false,
    },
  ],
  projectConstructionDepotBalances: [],
  projectExpenses: [],
  expenseDocuments: [],
  taskDependencies: [],
  taskAttachments: [],
  checklistItems: [],
  teamRoster: [],
};
